spring:
  application:
    name: spring_board
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true  # simple stdout sql in console
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comment: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
#      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    # test
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    # dev
    url: jdbc:postgresql://localhost:5432/spring_board
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
logging:
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
      total-size-cap: 300MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: D:\log\spring\logFile.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
